#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
#spring.jackson.time-zone=GMT+8
#spring.jackson.serialization.write-dates-as-timestamps=false

debug: true
spring:
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:192.168.0.104:8851,192.168.0.104:8850,192.168.0.104:8849}
server:
  port: 9090
feign:
  httpclient:
    connection-timeout: